name: "SQL Dacpac Build Action"
description: "Reusable action for building SQL db components."
inputs:
  repo_name:
    description: "Full repository name (owner/repo)"
    required: true
  version:
    description: "Version string (e.g., v1.2.3)"
    required: true
  component:
    description: "Component name (e.g., piggy-ui)"
    required: true
  personal_access_token:
    description: "GitHub Personal Access Token"
    required: true
outputs:
  VERSION:
    description: "The calculated version"
    value: ${{ inputs.version }}
runs:
  using: "composite"
  steps:
    - name: Checkout Component Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo_name }}
        token: ${{ inputs.personal_access_token }}
        ref: master
    - name: Find .sqlproj file and extract project name
      id: find_sqlproj
      run: |
        file=$(find . -name '*.sqlproj' | head -n 1)
        if [ -z "$file" ]; then
          echo "No .sqlproj file found!" >&2
          exit 1
        fi
        project_name=$(basename "$file" .sqlproj)
        echo "Found SQL project: $project_name ($file)"
        echo "project_name=$project_name" >> $GITHUB_OUTPUT
      shell: bash
    # Find msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    # create dacpac using MSBUILD
    - name: Build Database project
      run: |
        msbuild ${{ steps.find_sqlproj.outputs.project_name }}.sqlproj -property:Configuration=Release
      shell: pwsh
    # Publish artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.component }}-${{ inputs.version }}
        path: ${{ github.workspace }}/bin/Release/
    - name: Checkout Repository
      uses: actions/checkout@v4
